version: "3"

services:
  web:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    image: fft/web:latest
    env_file:
      - .env
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/fido
      - CELERY_BROKER_URL=rediss://redis:redis@redis:6379/0
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - db
      - redis

  celery:
    image: fft/web:latest
    env_file:
      - .env
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/fido
      - CELERY_BROKER_URL=rediss://redis:redis@redis:6379/0
    command: celery -A config worker -l info
    volumes:
      - ./:/app/
    depends_on:
      - db
      - redis

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=fido
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-bookworm
    ports:
      - "6379:6379"

  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 3gb
    depends_on:
      - web
    ports:
      - "4444:4444"
    profiles:
      - selenium
